language: python

matrix:
  include:
    - os: linux
      python: 2.7
      env: BUILD=PYPI
    - os: linux
      python: 3.4
    - os: linux
      python: 3.5
    - os: linux
      sudo: required
      python: 3.6
      env: BUILD=LINUX

before_install:
- ./.travis/before_install.sh

install:
- pip install -r requirements.txt
- pip install -r test-requirements.txt
- pip install pyinstaller

script:
- if [[ $TRAVIS_OS_NAME == 'osx' ]]; then python3 setup.py flake8; fi
- if [[ $TRAVIS_OS_NAME == 'linux' ]]; then python setup.py flake8; fi
- nose2 --with-coverage --coverage apsconnectcli/ --coverage-report xml

after_success:
- ./.travis/after_success.sh

deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: ovgNw6RwkcdXeD/NI6I+sSJutbr7PkgH5QQq3rDwcmBxu1kMn80EpqFYVe2NXBx493TlaO/+hA9WsCPDzyNVoFnt7xfJWE99K34/kQ8CKvKDYbu9EYvpul2U2uvDZx9a4M5ZxzaAInJrCDC348Dga4WCXl2yeLmyezIgpF3AxHiO+CJX3Lh7lod7P+U/3bRk1knBxtd4nMh8SABzpR+PX9qMnp2DQpb0ZAsm0jDkv5JXEuZW0a8bdcZwYLx4y1v8Hv70THkgl9dqG6FpUEFkG1ht4Peymr8voLdKHtl1fw/o7r9/+WFfZEwHkc4V7IGocDXyCRVuolQCiL5p4GxMwFB80zO9/LWGx8wgeVmVKXFGyLWurcP21FO9lbky3P/NeqsWyf6tPH7wCcsxl/Quw1LA2xk0xwdgwmffRMi9kXhi+JDkKM71CFVTGYlJFFd7zww5//tA15MPaD87vcQ151dnFD3yWlHGvonRNrVoWTQ5GSy/37/Gr70yt0zQz78HATT91BxN19wxAXpbxBqkoTcyDf80A7CmAwpA5BuVrzs7FNSXjZyWtJgPuSLYchmFHEhqjanEtBjM6CWFuACWkLK7Z+SYOhBHeQXOvvmSljEJzWGD7WCmsIiZyFxnHoUcb5MwsZIlltE6BmcqiAtIUNvonD4od/VLJjy7wzMLBLs=
    file: dist/apsconnect-mac
    on:
      tags: true
      all_branches: true
      repo: ingrammicro/apsconnect-cli
      condition: "$BUILD = OSX"

  - provider: releases
    skip_cleanup: true
    api_key:
      secure: ovgNw6RwkcdXeD/NI6I+sSJutbr7PkgH5QQq3rDwcmBxu1kMn80EpqFYVe2NXBx493TlaO/+hA9WsCPDzyNVoFnt7xfJWE99K34/kQ8CKvKDYbu9EYvpul2U2uvDZx9a4M5ZxzaAInJrCDC348Dga4WCXl2yeLmyezIgpF3AxHiO+CJX3Lh7lod7P+U/3bRk1knBxtd4nMh8SABzpR+PX9qMnp2DQpb0ZAsm0jDkv5JXEuZW0a8bdcZwYLx4y1v8Hv70THkgl9dqG6FpUEFkG1ht4Peymr8voLdKHtl1fw/o7r9/+WFfZEwHkc4V7IGocDXyCRVuolQCiL5p4GxMwFB80zO9/LWGx8wgeVmVKXFGyLWurcP21FO9lbky3P/NeqsWyf6tPH7wCcsxl/Quw1LA2xk0xwdgwmffRMi9kXhi+JDkKM71CFVTGYlJFFd7zww5//tA15MPaD87vcQ151dnFD3yWlHGvonRNrVoWTQ5GSy/37/Gr70yt0zQz78HATT91BxN19wxAXpbxBqkoTcyDf80A7CmAwpA5BuVrzs7FNSXjZyWtJgPuSLYchmFHEhqjanEtBjM6CWFuACWkLK7Z+SYOhBHeQXOvvmSljEJzWGD7WCmsIiZyFxnHoUcb5MwsZIlltE6BmcqiAtIUNvonD4od/VLJjy7wzMLBLs=
    file:
      - dist/apsconnect-lin
      - dist/apsconnect.exe
    on:
      tags: true
      all_branches: true
      repo: ingrammicro/apsconnect-cli
      condition: "$BUILD = LINUX"

  - provider: pypi
    user: apslite
    password:
      secure: Io3J3JjaumyIYetMV1jgPviQK9izAnU+Ok1LEjqGgg+3WiCy7eHjEVXOeLYy5hgv7UXgRIEqEN9DdZFGRnYvcf7MJqzeXilNNOBx7Y1L6pvpqhlJUHf7nEnJJ1002JBON6OvuMFDNxwAMVDVibZvGIMdRuFDBuHXmzvQFcyScwb0IK+0pnuxQx9y4GTZyZUNn2rmgLzmu7gkY6VcKnG1Knvs/PORGdYH7/XBRjiYgVKipAEns91ot18bs53GRKNSt6WfDBnjPjcH/mLMm4RNc0JbfK+WgQt+hj1UaJgwTZaOqcWOPB5EGjvc5ADP50eOyiDeyPLtrAYoSGwBqCeCoKSQ8bmuqkTxa1Ou2j2zUwyiA9hk2LG/VunhD7yaWxJPI2kTuGW91YWCK731W7C8Awb0gpFh7qA9PFcE9gkkJwh4c8aIJexDWxAx8+7BFFdNsjJf2phNzzgBl9LYcLPcVyNvtUr1YpqZGWGzlvrXdn0an1RmzN7vJhUZkwHEHpttj/M25YEcm1MVKyQhMxqiJwcYBc2qvIIHIWH3B/lxEp3vUk3nI5TfwMbozI4DavHD2oTnuSzNjqG6OOQnR8RGiBfZaZJyQeVgu4dvazVJeSpbxRJhK0Zh3XYJXisOar75vYZAjBh6TTL8H/LOWlg+pYAvH1QV5EQIVQN/08npnIc=
    on:
      tags: true
      all_branches: true
      distributions: sdist bdist_wheel
      repo: ingrammicro/apsconnect-cli
      condition: "$BUILD = PYPI"
